# Generated by Django 3.0.5 on 2020-04-23 20:34

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiccarapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator('^[0-9]{10}$', 'Invalid phone number')])),
                ('email', models.EmailField(max_length=254)),
                ('firstname', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator('^[a-zA-Z]+$', 'Only letters alllowed')])),
                ('lastname', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator('^[a-zA-Z]+$', 'Only letters alllowed')])),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='quiccarapp.User')),
            ],
        ),
    ]
