# Generated by Django 3.0.5 on 2020-05-12 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiccarapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ride',
            name='timeInserted',
        ),
        migrations.AlterField(
            model_name='ride',
            name='endHash',
            field=models.CharField(blank=True, db_index=True, max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='ride',
            name='startHash',
            field=models.CharField(blank=True, db_index=True, max_length=12, null=True),
        ),
    ]
