# Generated by Django 3.0.5 on 2020-05-15 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiccarapp', '0002_auto_20200513_0315'),
    ]

    operations = [
        migrations.CreateModel(
            name='PasswordReset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150)),
                ('token', models.CharField(max_length=16)),
                ('added', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
