# Generated by Django 3.0.5 on 2020-05-15 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiccarapp', '0003_passwordreset'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordreset',
            name='added',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
