# Generated by Django 3.0.5 on 2020-04-25 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiccarapp', '0003_auto_20200424_0208'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='email',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='firstname',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='lastname',
        ),
    ]
