# Generated by Django 3.0.5 on 2020-05-15 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiccarapp', '0004_auto_20200515_2244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordreset',
            name='username',
            field=models.CharField(max_length=150, unique=True),
        ),
    ]
