# Generated by Django 3.0.5 on 2020-04-25 15:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('quiccarapp', '0006_auto_20200425_2014'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ride',
            name='number',
        ),
        migrations.AddField(
            model_name='ride',
            name='user',
            field=models.OneToOneField(default=20, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
