# Generated by Django 3.0.5 on 2020-05-15 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiccarapp', '0006_auto_20200515_2258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordreset',
            name='added',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
