# Generated by Django 3.0.5 on 2020-04-25 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiccarapp', '0007_auto_20200425_2043'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ride',
            name='user',
        ),
    ]
