# Generated by Django 3.0.5 on 2020-04-25 15:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiccarapp', '0008_remove_ride_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='ride',
            name='number',
            field=models.CharField(default=111, max_length=10, validators=[django.core.validators.RegexValidator('^[0-9]{10}$', 'Invalid phone number')]),
            preserve_default=False,
        ),
    ]
