# Generated by Django 3.0.5 on 2020-05-19 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiccarapp', '0008_auto_20200515_2259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ride',
            name='endAddress',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='ride',
            name='startAddress',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
