# Generated by Django 3.0.5 on 2020-04-25 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiccarapp', '0009_ride_number'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Ride',
        ),
    ]
