# Generated by Django 3.0.5 on 2020-04-25 16:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('quiccarapp', '0012_auto_20200425_2128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ride',
            name='user',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
