# Generated by Django 3.0.5 on 2020-04-27 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiccarapp', '0013_auto_20200425_2204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ride',
            name='endHash',
            field=models.CharField(db_index=True, max_length=12),
        ),
        migrations.AlterField(
            model_name='ride',
            name='startHash',
            field=models.CharField(db_index=True, max_length=12),
        ),
    ]
